[general]
library_name = "librdkitcffi"
output_file_path = "../src/ctypes.jl"
module_name = ""
jll_pkg_name = ""
export_symbol_prefixes = []
prologue_file_path = "./prologue.jl"
output_ignorelist = [
    "RDKIT_RDKITCFFI_EXPORT",
    "RDKIT_RDKITCFFI_BUILD",
    "RDK_BUILD_INCHI_SUPPORT",
    "RDK_BUILD_AVALON_SUPPORT",
]
use_julia_native_enum_type = false
print_using_CEnum = false
use_deterministic_symbol = true
is_local_header_only = true
smart_de_anonymize = true
skip_static_functions = false
auto_mutability = false

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = false
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = false
use_ccall_macro = false
wrap_variadic_function = false

[codegen.macro]
macro_mode = "disable"
