module RDKit

using RDKit_jll
using JSON

# Layer 1: Auto-generated C bindings (generated by Clang.jl)
include("ctypes.jl")

# Layer 2: Core types and API macros
include("types.jl")
include("api.jl")

# Layer 3: High-level Julia API
include("io.jl")

# Exports
export Mol, Reaction
export get_mol, get_qmol, get_rxn
export get_smiles, get_smarts, get_cxsmiles, get_cxsmarts
export get_molblock, get_v3kmolblock, get_v2kmolblock
export get_json, get_inchi
export get_inchi_for_molblock, get_inchikey_for_inchi
export get_mol_frags
export get_morgan_fp, get_rdkit_fp, get_pattern_fp, get_atom_pair_fp, get_topological_torsion_fp, get_maccs_fp
export get_morgan_fp_as_bytes, get_rdkit_fp_as_bytes, get_pattern_fp_as_bytes, get_atom_pair_fp_as_bytes, get_topological_torsion_fp_as_bytes, get_maccs_fp_as_bytes
export get_descriptors
export get_svg, get_rxn_svg
export get_substruct_match, get_substruct_matches
include("drawing.jl")
include("calculators.jl")
# include("standardization.jl")
# include("coordinates.jl")
# include("modification.jl")
include("substructure.jl")
# include("properties.jl")
# include("png.jl")
# include("chirality.jl")
# include("logging.jl")

end # module
