module RDKit

using RDKit_jll
using JSON

# Layer 1: Auto-generated C bindings (generated by Clang.jl)
include("ctypes.jl")

# Layer 2: Core types and API macros
include("types.jl")
include("api.jl")

# Layer 3: High-level Julia API
# include("io.jl")
# include("drawing.jl")
# include("calculators.jl")
# include("standardization.jl")
# include("coordinates.jl")
# include("modification.jl")
# include("substructure.jl")
# include("properties.jl")
# include("png.jl")
# include("chirality.jl")
# include("logging.jl")

end # module
